- src/main/java/com/infomaniak/lib/core/utils/Extensions.kt
We need to be able to use a single instance of imageLoader instead of creating a new one every time the function is called
> Choose custom imageLoader when loading avatar

- build.gradle
LiveData 2.6.0 cause compilation error on kDrive, so we dissociate the version for kMail and kDrive
> Fix Core `liveData` version

- src/main/java/com/infomaniak/lib/core/auth/CredentialManager.kt
- src/main/java/com/infomaniak/lib/core/auth/TokenAuthenticator.kt
The bearerToken was not updated when the token was refreshed, so requests using it won't be updated either.
> fix: Update bearer token from TokenAuthenticator

- build.gradle
- schemas/com.infomaniak.lib.core.room.UserDatabase/5.json
- src/main/java/com/infomaniak/lib/core/InfomaniakCore.kt
- src/main/java/com/infomaniak/lib/core/api/ApiController.kt
- src/main/java/com/infomaniak/lib/core/room/UserDatabase.kt
Expires after 6 months of non-use
Depends on https://github.com/Infomaniak/android-login/pull/14
> Unlimited token

- src/main/java/com/infomaniak/lib/core/api/ApiRepositoryCore.kt
- src/main/java/com/infomaniak/lib/core/api/ApiRoutesCore.kt
The API used to work like this, the default avatars that actually point to somewhere was changed without our consent, so this only brings back the logic avatars were built with.
> Make default Avatars always null by removing the choice

- src/main/java/com/infomaniak/lib/core/auth/CredentialManager.kt
- src/main/java/com/infomaniak/lib/core/networking/HttpClient.kt
- src/main/java/com/infomaniak/lib/core/networking/HttpClientConfig.kt
- src/main/java/com/infomaniak/lib/core/utils/CoilUtils.kt
Up till now Stetho, Sentry and custom interceptors were not added in all our http clients. I factorized their addition so they are added everywhere and so we will be less likely to forget to add them if we ever create a new http client elsewhere
> Fix missing custom interceptors and sentry interceptor in some http clients

- src/main/java/com/infomaniak/lib/core/api/ApiController.kt
- src/main/java/com/infomaniak/lib/core/models/ApiError.kt
This is a temporary fix until we switch everything over to `kotlinx.serialization`
> Fix: When ApiError the context field throws an exception

- src/main/java/com/infomaniak/lib/core/networking/LiveDataNetworkStatus.kt
When several connections are available and the last has no Internet access, we publish that there is no connection even though the first has Internet access.
> fix: Sometimes no connection is received when multiple are available

- BugTracker/src/main/java/com/infomaniak/lib/bugtracker/BugTrackerActivity.kt
- src/main/java/com/infomaniak/lib/core/utils/Extensions.kt
The methods showProgress() and hideProgress() keep crashing on many occasions despite our best efforts to do things correctly. This PR wraps the methods that throw to avoid crashing
> Prevent showing and hiding progress crashes

- build.gradle
Revert rebolectric because it breaks tests in kDrive
> Downgrade robolectric

- Stores/src/standard/java/com/infomaniak/lib/stores/AppUpdateScheduler.kt
The PlayServices are throwing a lot of maybe not so meaningful stuff.
We are trying to log it to better understand the situation.
> Catch PlayServices AppUpdate exceptions to better understand what's happening

- src/main/java/com/infomaniak/lib/core/views/EndIconTextInputLayout.kt
The same padding bug exists on the error end icon. This PR applies the same fix to this error icon as well
> Also handle error icon's end padding in EndIconTextInputLayout

- src/main/java/com/infomaniak/lib/core/auth/TokenAuthenticator.kt
- src/main/java/com/infomaniak/lib/core/auth/TokenInterceptor.kt
Remove because it happens because the user is disconnected due to a 401 error from another call before.
> Remove sentry only called when receiving 401

- src/main/java/com/infomaniak/lib/core/models/ApiResponse.kt
- src/main/java/com/infomaniak/lib/core/models/ApiResponseStatus.kt
These fields are needed for the public share link feature
> Add `Redirect` and `uri` in ApiResponse

- src/main/java/com/infomaniak/lib/core/api/ApiController.kt
- src/main/java/com/infomaniak/lib/core/auth/TokenAuthenticator.kt
- src/main/java/com/infomaniak/lib/core/networking/AccessTokenUsageInterceptor.kt
- src/main/java/com/infomaniak/lib/core/utils/ApiTokenExt.kt
- src/main/java/com/infomaniak/lib/core/utils/TokenUtils.kt
Having an infinite token means you will never be able to refresh your token, so there should not be an exception while trying to do so. This will remove unimportant RefreshTokenException thrown by infinite tokens in Sentry
> Stop throwing RefreshTokenException when the user has an infinite token

- AppLock/build.gradle
- AppLock/src/main/java/com/infomaniak/lib/applock/DisplayState.kt
- AppLock/src/main/java/com/infomaniak/lib/applock/LockActivity.kt
This new function encapsulates the complexity of app locking, so that the use-site becomes much simpler:
Calling the function in the target Activity's onCreate is all that's needed now.
Having logic split between onPause() and onResume() can now be a thing of the past.
> feat: Introduce LockActivity.scheduleLockIfNeeded with new feature

- AppLock/build.gradle
- AppLock/src/main/java/com/infomaniak/lib/applock/LockActivity.kt
- AppLock/src/main/java/com/infomaniak/lib/applock/Utils.kt
1. Use SystemClock.elapsedRealtime() instead of System.currentTimeMillis(),
so it's not possible to unlock the app by setting the time in the past.
2. Ensure the app starts locked if the system had to kill the process.
3. Ensure all tasks get the lock when screen lock triggers app lock
> fix: Block app lock hacking

- AppLock/src/main/java/com/infomaniak/lib/applock/LockActivity.kt
This will allow client apps to call this new LockActivity.unlock() function when biometrics have been confirmed right after a request to enable the app lock.
> chore: Extract an unlock function to avoid double lock

- gradle/core.versions.toml
- src/main/kotlin/com/infomaniak/core/EnumUtils.kt
Now that we write enums with PascalCase we can't always use the `enumValueOfOrNull` and base the recognition on the name of the enum value. So I added a helper method to easily get an enum instance for any enum that extends the ApiEnum interface. The interface only requires the children to implement an `apiValue` field that will be used to match the input string. The helper method is pretty similar to the existing `enumValueOfOrNull` but with a different name.
Downgrading androidxCore was necessary to use the module on Mail for the time being.
> feat: Add ApiEnum and apiEnumValueOfOrNull helper methods

- Legacy/src/main/java/com/infomaniak/lib/core/auth/TokenInterceptor.kt
- Legacy/src/main/java/com/infomaniak/lib/core/networking/AccessTokenUsageInterceptor.kt
The validity limit without use as been modified from 2 months up to 6 months on the API
> feat: Update the limit before sending a sentry about access token errors

- src/main/kotlin/com/infomaniak/core/utils/EnumUtils.kt
Up till now, I only needed to read from an ApiEnum backing field so calling `apiEnumValueOfOrNull` everywhere was enough. But now I will also need to mutate this field so, to make it easier to manipulate I created this delegate that can be used as such:
```kt
class Example {
private var _snoozeState: String? = null
var snoozeState: SnoozeState? by apiEnum(::_snoozeState)
}
```
> feat: Add a delegate to read and mutate an apiEnum backingfield seamlessly

- Legacy/src/main/java/com/infomaniak/lib/core/utils/Extensions.kt
For the snooze feature, there's a situation where I'm in a BottomSheet, I show an AlertDialog and close the BottomSheet, and when the user clicks on the positive button, I need to initiate a navigation.
When the user clicks on the positive button, since the BottomSheet is no more, calling `findNavController()` on the BottomSheet that's gone crashes because it can't find any NavController.
But the `navController` can be "found" before closing the BottomSheet and displaying the AlertDialog, and therefore when the user clicks on the positive button, the reste of the navigation can be executed on the already "found" `navController`.
For this reason, I need to expose a `canNavigate()` method that directly works with a NavController.
> feat: Expose a canNavigate() directly accessible on any NavController

- FragmentNavigation/build.gradle.kts
- FragmentNavigation/proguard-rules.pro
- FragmentNavigation/src/main/java/com/infomaniak/core/fragmentnavigation/FragmentNavigationExt.kt
- Legacy/src/main/java/com/infomaniak/lib/core/utils/Extensions.kt
Old navigation methods were bugged as described in the deprecation messages. This PR deprecates them and introduces new fixed ones in the new core. 
We changed the name to be able to have different signatures and so we can still use the deprecated version alongside the new version in the same file
> feat: Deprecate old safe navigation methods and introduce new ones

- Legacy/src/main/java/com/infomaniak/lib/core/api/ApiController.kt
- Legacy/src/main/java/com/infomaniak/lib/core/api/InternalTranslatedErrorCode.kt
- Legacy/src/main/java/com/infomaniak/lib/core/models/ApiResponse.kt
- Legacy/src/main/java/com/infomaniak/lib/core/utils/ApiErrorCode.kt
This required to handle error messages that were translated through `ApiResponse.translatedError` and also translate them through the new alternative `translateError()`.
At the same time, we took this opportunity to replace the ServerError message that was displayed to the user when receiving a 500 with the generic "an error has occurred" to not give useless info to the user and be iso with iOS.
> feat: Deprecate ApiResponse.translatedError

- AppIntegrity/build.gradle.kts
- MyKSuite/build.gradle.kts
- WebView/build.gradle.kts
- gradle/core.versions.toml
This will avoid locking project to old dependencies because a project can't update.
Instead, versions can be defined in host projects.
> chore: Remove versions of Gradle plugins

- src/main/kotlin/com/infomaniak/core/utils/EmailUtils.kt
The regex comes from what iOS was using in mail. Thanks to this update, we support more valid email adresses and we are more iso.
To get a truly generic method that can be used for the mail app I had to remove the trim() part of the logic, but it was only used in the SwissTransfer app and can be fixed there instead
> feat: Use new valid email detection regex that matches closer to RFC5321

- RecyclerView/src/main/kotlin/com/infomaniak/core/recyclerview/CoroutineScopeViewHolder.kt
- RecyclerView/src/main/kotlin/com/infomaniak/core/recyclerview/ResettableLazy.kt
The stacktrace of the crash this PR fixes:
```stacktrace
E  FATAL EXCEPTION: main
Process: com.infomaniak.drive, PID: 19774
java.lang.IllegalStateException: Provide a parentScope in the constructor, or make the Adapter implement LifecycleOwner
at com.infomaniak.core.recyclerview.CoroutineScopeViewHolder.currentBindScopeDelegate$lambda$0(CoroutineScopeViewHolder.kt:45)
at com.infomaniak.core.recyclerview.CoroutineScopeViewHolder.$r8$lambda$Brz_99wuy1DcSDOhnTr-z2XXPE8(Unknown Source:0)
at com.infomaniak.core.recyclerview.CoroutineScopeViewHolder$$ExternalSyntheticLambda0.invoke(D8$$SyntheticClass:0)
at com.infomaniak.core.recyclerview.ResettableLazy.getValue(ResettableLazy.kt:30)
at com.infomaniak.core.recyclerview.CoroutineScopeViewHolder.getCurrentBindScope(CoroutineScopeViewHolder.kt:49) …
```
> fix: Fix rare crash that could occur on view recycling

- src/main/kotlin/com/infomaniak/core/AtomicCoroutines.kt
- src/main/kotlin/com/infomaniak/core/Flow.kt
- src/main/kotlin/com/infomaniak/core/SendChannel.kt
This commit also exposes its 2 foundations:
`trySelectAtomically`, and `sendAtomic` for `SendChannel<T>`.
This code was [in SwissTransfer](https://github.com/Infomaniak/android-SwissTransfer/blob/e2729a6acb6d2cf4b01a2311b31a0a143410b1a0/app/src/main/java/com/infomaniak/swisstransfer/upload/UploadForegroundService.kt#L208-L265) and will be used in kDrive too, going forward, so it's time to set it up for reuse.
> chore: Extract the rateLimit operator for Flow

- Legacy/src/main/java/com/infomaniak/lib/core/auth/CredentialManager.kt
This was preventing uploads to succeed on kDrive if the upload bandwidth was smaller than 14Mbps:
((50 * 1024 * 1024 * 8 * 4) / 120) / 1000 = 13,9810133333
Full breakdown
```
(
(
50 * 1024 [kio] * 1024 [Mio] * 8 [Mb] *
4 [parallel chunks]
) / 120 [s]
) / 1000 [kbps] / 1000 [Mbps]
```
We're now leaving the default, which is no timeout. Timeout for read, write, and connection, are enough.
> fix: Remove too short callTimeout

- Ktor/build.gradle.kts
- Ktor/proguard-rules.pro
- Ktor/src/main/kotlin/com/infomaniak/core/ktor/InputStreamToOutgoingContent.kt
- src/main/kotlin/com/infomaniak/core/io/InputStream.kt
`skipExactly` was copied from [SwissTransfer here](https://github.com/Infomaniak/android-SwissTransfer/blob/e2729a6acb6d2cf4b01a2311b31a0a143410b1a0/app/src/main/java/com/infomaniak/swisstransfer/upload/UriToOutgoingContent.kt#L52-L81), and `Inpustream.toOutgoingContent` was inspired by `Uri.toOutgoingContent` from [SwissTransfer here](https://github.com/Infomaniak/android-SwissTransfer/blob/e2729a6acb6d2cf4b01a2311b31a0a143410b1a0/app/src/main/java/com/infomaniak/swisstransfer/upload/UriToOutgoingContent.kt#L35-L50).
> feat: InputStream extensions

- Compose/MaterialThemeFromXml/build.gradle.kts
- Compose/MaterialThemeFromXml/src/main/kotlin/com/infomaniak/core/compose/materialthemefromxml/MaterialThemeFromXml.kt
We often need to use jetpack compose code inside of projects defined in xml and the material theme is only defined at the xml level in these projects. This PR adds a module that defines a composable method that will automatically take all xml defined material colors and set them inside a jetpack compose MaterialTheme. This way we can easily code jetpack compose UI that adapt to each app's theme
> feat: Automatically define a jetpack compose MaterialTheme based on the theme defined in xml

- Legacy/src/main/java/com/infomaniak/lib/core/api/ApiController.kt
- Legacy/src/main/java/com/infomaniak/lib/core/models/ApiResponse.kt
All `ApiError` was overridden by `UnknownError` when receiving correctly formed error response and if error code was under `500`.
> fix: Don't replace api error on correctly formed 'ApiResponse'

- Compose/Basics/build.gradle.kts
- Compose/MaterialThemeFromXml/build.gradle.kts
- FileTypes/build.gradle.kts
- Onboarding/build.gradle.kts
- Thumbnails/build.gradle.kts
Since kotlin 2.0, this is not needed anymore. Thanks @LouisCAD for the notice
> refactor: Remove unnecessary kotlinCompilerExtensionVersion

- CrossAppLogin/build.gradle.kts
- CrossAppLogin/proguard-rules.pro
- CrossAppLogin/src/main/kotlin/com/infomaniak/core/login/crossapp/BaseCrossAppLoginProvider.kt
- CrossAppLogin/src/main/kotlin/com/infomaniak/core/login/crossapp/BaseCrossAppLoginService.kt
- CrossAppLogin/src/main/kotlin/com/infomaniak/core/login/crossapp/CrossAppLogin.kt
- CrossAppLogin/src/main/kotlin/com/infomaniak/core/login/crossapp/ExternalAccount.kt
- CrossAppLogin/src/main/kotlin/com/infomaniak/core/login/crossapp/internal/ChannelMessageHandler.kt
- CrossAppLogin/src/main/kotlin/com/infomaniak/core/login/crossapp/internal/DisposableMessage.kt
- CrossAppLogin/src/main/kotlin/com/infomaniak/core/login/crossapp/internal/LocalAccounts.kt
- CrossAppLogin/src/main/kotlin/com/infomaniak/core/login/crossapp/internal/SingleBlobCursor.kt
- CrossAppLogin/src/main/kotlin/com/infomaniak/core/login/crossapp/internal/certificates/AppCertificateChecker.kt
- CrossAppLogin/src/main/kotlin/com/infomaniak/core/login/crossapp/internal/certificates/AppCertificateCheckerImpl.kt
- CrossAppLogin/src/main/kotlin/com/infomaniak/core/login/crossapp/internal/certificates/AppSigningCertificates.kt
- CrossAppLogin/src/main/kotlin/com/infomaniak/core/login/crossapp/internal/certificates/LazyAppSigningCertificate.kt
- CrossAppLogin/src/main/kotlin/com/infomaniak/core/login/crossapp/internal/certificates/infomaniakAppsCertificates.kt
- Legacy/build.gradle
- Legacy/src/main/java/com/infomaniak/lib/core/room/UserDao.kt
- Legacy/src/main/java/com/infomaniak/lib/core/room/UserDatabase.kt
- gradle/core.versions.toml
- src/main/kotlin/com/infomaniak/core/Flow.kt
- src/main/kotlin/com/infomaniak/core/Racing.kt
For the curious minds, [here is the doc on bound services](https://developer.android.com/develop/background-work/services/bound-services), one the ways to do IPC (inter-process communication) on Android.
Another way is using `ContentProvider`, which is also prototyped in this PR.
> feat(CrossAppLogin): Add CrossAppLogin façade + IPC server impl

- Legacy/src/main/java/com/infomaniak/lib/core/room/UserDatabase.kt
The problem will be fixed by adding an `injectAsAppCtx()` call in the Application class' init block.
> chore: Revert re-adding of the Context parameter

- WebView/build.gradle.kts
- gradle/core.versions.toml
This required to adapt some of the code because of the breaking changes that come with the latest version. Also we don't need to specify compose foundation's version by hand. Now we can use the compose bom version's instead
> feat: Bump compose bom to the latest version

- CrossAppLogin/src/main/kotlin/com/infomaniak/core/login/crossapp/internal/deviceinfo/AbstractDeviceInfoUpdateWorker.kt
- CrossAppLogin/src/main/kotlin/com/infomaniak/core/login/crossapp/internal/extensions/UuidForKotlin2.kt
> fix: Make DeviceId works with Kotlin 2.0 (because of Realm Kotlin that can't be bumped to Kotlin 2.1)

- Legacy/src/main/java/com/infomaniak/lib/core/utils/SentryLog.kt
When you use `withScope` with a SentryLog, it doesn't work because you have to pass the scope directly to the event.
So now `SentryLog.e` or `wtf` can take a scopeCallback as a parameter.
> feat: Add possibility to custom the scope from SentryLog.e

- MyKSuite/build.gradle.kts
- MyKSuite/src/main/java/com/infomaniak/core/myksuite/ui/data/AvatarData.kt
- MyKSuite/src/main/java/com/infomaniak/core/myksuite/ui/screens/MyKSuiteDashboardScreen.kt
- MyKSuite/src/main/java/com/infomaniak/core/myksuite/ui/utils/MyKSuiteUiUtils.kt
Now that we have a new more generic Avatar composable, we can quickly replace the only usage of UserAvatar that was in the MyKsuite module with the new Avatar module to avoid having to support deprecated code.
To avoid modifying the MyKsuite module too much, I copied the AvatarData data class inside of the MyKsuite module so the module can continue to use it and I simply turned it into the required AvatarType at the end.
For now, I did not delete the UserAvatar module because there's another branch which is not yet merged that started using UserAvatar and I would like to talk in perso with the person working on that branch
> refactor: Replace UserAvatar module with Avatar

- Compose/BasicButton/build.gradle.kts
- Compose/BasicButton/src/main/kotlin/com/infomaniak/core/compose/basicbutton/BasicButton.kt
Extract a basic button jetpack compose component to its own module so we can easily reuse functionalities across apps. For now it only has the loading functionality. This got extracted and slightly adapted to make it more generic from the SwissTransfer version which was already very generic
> feat: Create a module for the BasicButton component

- Auth/src/main/kotlin/com/infomaniak/core/auth/api/ApiController.kt
- CrossAppLogin/Back/src/main/kotlin/com/infomaniak/core/crossapplogin/back/DerivedTokenGeneratorImpl.kt
- Legacy/src/main/java/com/infomaniak/lib/core/api/ApiController.kt
- Legacy/src/main/java/com/infomaniak/lib/core/fdroidTools/FdroidApiTools.kt
- Legacy/src/main/java/com/infomaniak/lib/core/githubTools/GitHubViewModel.kt
- Legacy/src/main/java/com/infomaniak/lib/core/utils/OkHttpClientExt.kt
- Network/src/main/kotlin/com/infomaniak/core/network/api/ApiController.kt
- Network/src/main/kotlin/com/infomaniak/core/network/utils/OkHttpClientExt.kt
That is because it will synchronously look into the cache on the device storage.
Caught thanks to StrictMode.
Stacktrace:
```stacktrace
StrictMode policy violation; ~duration=6 ms: android.os.strictmode.DiskReadViolation
at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1683)
at libcore.io.BlockGuardOs.access(BlockGuardOs.java:74)
at libcore.io.ForwardingOs.access(ForwardingOs.java:128)
at android.app.ActivityThread$AndroidOs.access(ActivityThread.java:8582)
at java.io.UnixFileSystem.checkAccess(UnixFileSystem.java:332)
at java.io.File.exists(File.java:829)
at okhttp3.internal.io.FileSystem$Companion$SystemFileSystem.delete(FileSystem.kt:77)
at okhttp3.internal.io.FileSystem$Companion$SystemFileSystem.rename(FileSystem.kt:88)
at …
```
> perf: Run OkHttp's response.body.string() on Dispatchers.IO

- Avatar/src/main/java/com/infomaniak/core/avatar/components/UrlAvatar.kt
Avatars that were loading a url would not display at all during the loading state. Now if the url avatar is loading, display the initials as a placeholder.
Access the image painter state instead of using SubcomposeAsyncImage for the increased performances as described in the documentation
> feat: Display initials while in the loading state when loading an url avatar

- .github/workflows/auto-author-assign.yml
- .github/workflows/dependent-issues.yml
- .github/workflows/rebase-default-branch.yml
- .github/workflows/semantic-commit.yml
Adds missing concurrency group block to github workflows. Also bumps version of github actions
> chore: Bump github actions versions and add concurrency groups

- .github/workflows/translations-validation.yml
The ksuite module was renamed without renaming the path for the strings validation CI which broke tests. Also, a new ksuite pro module with strings was added but it wasn't specified in the strings CI
> feat: Fix ksuite rename in strings ci and add missing ksuite pro check

- Compose/Preview/build.gradle.kts
- Compose/Preview/src/main/kotlin/com/infomaniak/core/compose/preview/MultiplePreviews.kt
I will use annotation preview created for SwissTransfer in kMail. Instead of duplicating the code, I moved it to core to share it.
> feat: Share multiple annotation preview used in SwissTransfer
