src/main/java/com/infomaniak/lib/core/utils/Extensions.kt

Add the generic isContentEqual() function to core, to compare 2 lists

Add isContentEqual to core

---

BugTracker/src/main/java/com/infomaniak/lib/bugtracker/BugTrackerActivity.kt
BugTracker/src/main/java/com/infomaniak/lib/bugtracker/BugTrackerViewModel.kt

- Fix sentry https://sentry.infomaniak.com/share/issue/94897e0c2f264075bb1a458ff4ae6667/
- Improve send bug report logic

fix: animators may only be run on Looper threads

---

src/main/java/com/infomaniak/lib/core/utils/DownloadManagerUtils.kt

Fix download error caused by leak

Close query to avoid leak and download error

---

src/main/java/com/infomaniak/lib/core/InfomaniakCore.kt
src/main/java/com/infomaniak/lib/core/networking/HttpUtils.kt

The bearer token becomes optional

fix: Not initialized bearer token for services

---

src/main/java/com/infomaniak/lib/core/utils/Extensions.kt

Only navigate if the direction action exists in the current destination

fix: IllegalArgumentException from safeNavigate for a direction

---

src/main/java/com/infomaniak/lib/core/views/LoaderTextView.kt

Handle `maxWidth` for LoaderTextView

---

src/main/java/com/infomaniak/lib/core/utils/SentryLog.kt

This is the first version, see if any further modifications are required.

feat: Add SentryLog

---

src/main/java/com/infomaniak/lib/core/api/ApiController.kt
src/main/java/com/infomaniak/lib/core/models/ApiResponse.kt
src/main/java/com/infomaniak/lib/core/models/ApiResponseStatus.kt
src/main/java/com/infomaniak/lib/core/models/IApiResponse.kt

kDrive need a custom ApiResponse for cursor

feat: Making the ApiResponse class customisable

---

Stores/src/fdroid/java/com.infomaniak.lib.stores/StoreUtils.kt
Stores/src/standard/java/com.infomaniak.lib.stores/StoreUtils.kt

Support background update

---

build.gradle
src/main/java/com/infomaniak/lib/core/auth/CredentialManager.kt
src/main/java/com/infomaniak/lib/core/networking/HttpClient.kt
src/main/java/com/infomaniak/lib/core/room/UserDao.kt

- Update `Room` to 2.6.1
- Update `Sentry` to 7.0.0
- Migrate `Kotlin` to 1.9.21

Support kotlin 1.9

---

Stores/src/fdroid/java/com.infomaniak.lib.stores/StoreUtils.kt
Stores/src/standard/java/com.infomaniak.lib.stores/StoreUtils.kt

Remove legacy update functions

---

Stores/src/main/java/com/infomaniak/lib/stores/BaseInAppUpdateManager.kt
Stores/src/main/java/com/infomaniak/lib/stores/StoresViewModel.kt
Stores/src/standard/java/com/infomaniak/lib/stores/updatemanagers/InAppUpdateManager.kt

Fix bottomsheet being instanced several times

---

src/main/java/com/infomaniak/lib/core/networking/GZipInterceptor.kt
src/main/java/com/infomaniak/lib/core/networking/HttpClient.kt
src/main/java/com/infomaniak/lib/core/networking/HttpUtils.kt

Tested on kDrive. Seems to be working fine.

Add gzip interceptor to be able to unzip API response

---

BugTracker/src/main/java/com/infomaniak/lib/bugtracker/BugTrackerActivity.kt
src/main/java/com/infomaniak/lib/core/utils/FilePicker.kt

Waiting for a full Draft UI logic revamp.
Edit : it's done ! https://github.com/Infomaniak/android-kMail/pull/1759

Fix picker not calling callback when activity is recreated

---

Stores/src/main/res/values/styles.xml
Stores/src/standard/java/com/infomaniak/lib/stores/reviewmanagers/InAppReviewManager.kt

Use the right color to avoid having a black text in dark mode

---

Stores/src/standard/java/com/infomaniak/lib/stores/ui/dialogs/ReviewAlertDialog.kt

Allow canceling the dialog

---

AppLock/src/main/java/com/infomaniak/lib/applock/LockActivity.kt
BugTracker/src/main/java/com/infomaniak/lib/bugtracker/BugTrackerActivity.kt
src/main/java/com/infomaniak/lib/core/api/ApiController.kt
src/main/java/com/infomaniak/lib/core/networking/HttpClientConfig.kt
src/main/java/com/infomaniak/lib/core/utils/DownloadManagerUtils.kt

Added some `_` to split `000`  groups, and some `L` to precise when it's a Long.
Also added explanatory comment to directly know the size of a number.

Format some numbers to enhance readability

---

src/main/java/com/infomaniak/lib/core/utils/Extensions.kt

Send current textColor to `initProgress()` so it'll be able to restore it when progress is done

---

AppLock/src/main/java/com/infomaniak/lib/applock/Utils.kt
Stores/src/main/res/layout/activity_feedback_webview.xml
src/main/java/com/infomaniak/lib/core/utils/Utils.kt

Auto-reformat on the whole project by Android Studio.

Auto-format code

---

src/main/java/com/infomaniak/lib/core/networking/NetworkAvailability.kt

Fix MAIL-ANDROID-EX5
There is a crash because of a concurrent read and write in NetworkAvailability

Fix a crash in NetworkAvailability

---

MykSuite/build.gradle.kts
MykSuite/src/main/java/com/infomaniak/lib/myksuite/ui/screens/MyKSuiteUpgradeFeature.kt
MykSuite/src/main/java/com/infomaniak/lib/myksuite/ui/views/BaseMyKSuiteChipView.kt
MykSuite/src/main/java/com/infomaniak/lib/myksuite/ui/views/MyKSuiteChipView.kt
MykSuite/src/main/java/com/infomaniak/lib/myksuite/ui/views/MyKSuitePlusChipView.kt
MykSuite/src/main/java/com/infomaniak/lib/myksuite/ui/views/MyKSuiteUpgradeBottomSheetDialog.kt
MykSuite/src/main/res/navigation/my_ksuite_navigation.xml
gradle/core.versions.toml

feat(MyKSuite-03): Wrap compose components in xml views

---

MykSuite/src/main/java/com/infomaniak/lib/myksuite/ui/screens/MyKSuiteDashboardScreen.kt
MykSuite/src/main/java/com/infomaniak/lib/myksuite/ui/screens/components/LimitedFunctionnalities.kt
MykSuite/src/main/java/com/infomaniak/lib/myksuite/ui/views/MyKSuiteDashboardFragment.kt
MykSuite/src/main/res/navigation/my_ksuite_navigation.xml
MykSuite/src/main/res/values-night/colors.xml
MykSuite/src/main/res/values/colors.xml
MykSuite/src/main/res/values/strings.xml

feat(MyKSuite-05): Wrap Dashboard fragment in xml

---

MykSuite/src/main/java/com/infomaniak/lib/myksuite/ui/components/MyKSuiteChips.kt
MykSuite/src/main/java/com/infomaniak/lib/myksuite/ui/screens/MyKSuiteDashboardScreen.kt
MykSuite/src/main/java/com/infomaniak/lib/myksuite/ui/views/BaseMyKSuiteChipView.kt
MykSuite/src/main/java/com/infomaniak/lib/myksuite/ui/views/MyKSuiteChipView.kt
MykSuite/src/main/java/com/infomaniak/lib/myksuite/ui/views/MyKSuitePlusChipView.kt

In fact these chip aren't clickable anywhere, so it's more of an Image with a rounded background.
Also material chip force an internal padding that make it looks too big compared to the figma
Depends on #267

refactor(MyKSuite-06): Use image with background instead of material Chip

---

MykSuite/src/main/java/com/infomaniak/core/myksuite/ui/components/MyKSuiteChips.kt
MykSuite/src/main/java/com/infomaniak/core/myksuite/ui/screens/MyKSuiteDashboardScreen.kt
MykSuite/src/main/java/com/infomaniak/core/myksuite/ui/screens/MyKSuiteUpgradeBottomSheet.kt
MykSuite/src/main/java/com/infomaniak/core/myksuite/ui/screens/components/AppStorageQuotas.kt
MykSuite/src/main/java/com/infomaniak/core/myksuite/ui/screens/components/ButtonType.kt
MykSuite/src/main/java/com/infomaniak/core/myksuite/ui/screens/components/ExpandableItemView.kt
MykSuite/src/main/java/com/infomaniak/core/myksuite/ui/screens/components/LimitedFunctionnalities.kt
MykSuite/src/main/java/com/infomaniak/core/myksuite/ui/screens/components/UpgradeFeature.kt
MykSuite/src/main/java/com/infomaniak/core/myksuite/ui/screens/components/UserAvatar.kt
MykSuite/src/main/java/com/infomaniak/core/myksuite/ui/theme/Theme.kt

refactor(MyKSuite-08): Delete kSuite theme object

---

MykSuite/src/main/java/com/infomaniak/core/myksuite/ui/components/MyKSuitePrimaryButton.kt
MykSuite/src/main/java/com/infomaniak/core/myksuite/ui/screens/MyKSuiteUpgradeBottomSheet.kt
MykSuite/src/main/java/com/infomaniak/core/myksuite/ui/screens/components/AppStorageQuotas.kt
MykSuite/src/main/java/com/infomaniak/core/myksuite/ui/screens/components/ExpandableItemView.kt
MykSuite/src/main/java/com/infomaniak/core/myksuite/ui/screens/components/LimitedFunctionnalities.kt
MykSuite/src/main/java/com/infomaniak/core/myksuite/ui/screens/components/MyKSuiteButtonType.kt
MykSuite/src/main/java/com/infomaniak/core/myksuite/ui/screens/components/UpgradeFeature.kt
MykSuite/src/main/java/com/infomaniak/core/myksuite/ui/screens/components/UserAvatar.kt
MykSuite/src/main/java/com/infomaniak/core/myksuite/ui/theme/Theme.kt
MykSuite/src/main/java/com/infomaniak/core/myksuite/ui/views/MyKSuiteUpgradeBottomSheetDialog.kt

refactor(MyKSuite-09): Mark as internal concerned functions and class that doesn't need to be exposed

---

Legacy/build.gradle

Depends on https://github.com/Infomaniak/android-login/pull/21

chore: Bump Login

---

Compose/Basics/src/main/kotlin/com/infomaniak/core/compose/basics/CallableState.kt
Legacy/BugTracker/src/main/java/com/infomaniak/lib/bugtracker/BugTrackerActivity.kt
Legacy/Stores/src/main/java/com/infomaniak/lib/stores/updaterequired/UpdateRequiredActivity.kt
Legacy/build.gradle
Legacy/src/main/java/com/infomaniak/lib/core/extensions/AppCompatActivityExtensions.kt
Legacy/src/main/java/com/infomaniak/lib/core/utils/Extensions.kt
Legacy/src/main/java/com/infomaniak/lib/core/utils/NotificationUtilsCore.kt
Network/src/main/kotlin/com/infomaniak/core/network/NetworkAvailability.kt
Notifications/src/main/kotlin/com/infomaniak/core/notifications/NotificationsUtilsCore.kt
build.gradle.kts
src/main/kotlin/com/infomaniak/core/ForegroundService.kt
src/main/kotlin/com/infomaniak/core/FormatterFileSize.kt

Depends on https://github.com/Infomaniak/android-login/pull/25

refactor: Bump Core to minSdk 24

---

src/main/kotlin/com/infomaniak/core/FormatterFileSize.kt

feat: Handle petabyte in FormatterFileSize

---

MyKSuite/build.gradle.kts
MyKSuite/src/main/java/com/infomaniak/core/myksuite/ui/theme/ColorsDark.kt
MyKSuite/src/main/java/com/infomaniak/core/myksuite/ui/theme/ColorsLight.kt
MyKSuite/src/main/java/com/infomaniak/core/myksuite/ui/theme/Theme.kt

I kept on overriding previous material themE values to not alter the existing logic

refactor: Use the new MaterialThemeFromXml inside MyKSuite module

---

Legacy/src/main/java/com/infomaniak/lib/core/InfomaniakCore.kt

This will be needed for the emoji reaction feature

feat: Don't limit InfomaniakCore.apiErrorCodes to ApiErrorCode when we can use ErrorCodeTranslated

---

Legacy/src/main/java/com/infomaniak/lib/core/networking/AccessTokenUsageInterceptor.kt

First, sometimes at the deconnection, we couldn't get the api token, so a `runBlocking` was added in hope that we'll always have a token. 
But adding this make the code wait forever because when there is no account yet, the flow is empty.
As all our tokens are now infinite, we drop the check because it's the only reason why we had to have the token here in the first place

fix: Fix app's first connection by considering all token infinite

---

CrossAppLogin/build.gradle.kts
CrossAppLogin/src/main/kotlin/com/infomaniak/core/login/crossapp/BaseCrossAppLoginService.kt
CrossAppLogin/src/main/kotlin/com/infomaniak/core/login/crossapp/BasicDataParceling.kt
CrossAppLogin/src/main/kotlin/com/infomaniak/core/login/crossapp/CrossAppDeviceIdRequest.kt
CrossAppLogin/src/main/kotlin/com/infomaniak/core/login/crossapp/CrossAppLogin.kt
CrossAppLogin/src/main/kotlin/com/infomaniak/core/login/crossapp/CrossAppLoginImpl.kt
CrossAppLogin/src/main/kotlin/com/infomaniak/core/login/crossapp/ExternalAccount.kt
CrossAppLogin/src/main/kotlin/com/infomaniak/core/login/crossapp/IpcIssuesManager.kt
CrossAppLogin/src/main/kotlin/com/infomaniak/core/login/crossapp/IpcIssuesManagerImpl.kt
CrossAppLogin/src/main/kotlin/com/infomaniak/core/login/crossapp/internal/deviceid/SharedDeviceIdManager.kt
CrossAppLogin/src/main/kotlin/com/infomaniak/core/login/crossapp/internal/deviceid/SharedDeviceIdManagerImpl.kt
CrossAppLogin/src/main/kotlin/com/infomaniak/core/login/crossapp/internal/deviceid/SharedDeviceIdStorage.kt
CrossAppLogin/src/main/kotlin/com/infomaniak/core/login/crossapp/internal/deviceinfo/AbstractDeviceInfoUpdateWorker.kt
CrossAppLogin/src/main/kotlin/com/infomaniak/core/login/crossapp/internal/deviceinfo/DeviceInfo.kt
CrossAppLogin/src/main/kotlin/com/infomaniak/core/login/crossapp/internal/deviceinfo/DeviceInfoUpdateManager.kt
Legacy/src/main/java/com/infomaniak/lib/core/api/ApiRoutesCore.kt
src/main/kotlin/com/infomaniak/core/ConcurrentOperators.kt
src/main/kotlin/com/infomaniak/core/extensions/AtomicFileExt.kt

Probably best suited for pair-reviewing.
Depends on #380

feat: Cross-app device id

---

Avatar/build.gradle.kts
Avatar/src/main/java/com/infomaniak/core/avatar/AvatarColors.kt
Avatar/src/main/java/com/infomaniak/core/avatar/AvatarType.kt
Avatar/src/main/java/com/infomaniak/core/avatar/AvatarUrlData.kt
Coil/src/main/java/com/infomaniak/core/coil/CoiXmllExt.kt

Only define the generic data models to display any kind of avatars for now

feat: Create avatar module with data models

---

Auth/build.gradle.kts
Legacy/build.gradle
Matomo/build.gradle.kts
MyKSuite/src/main/java/com/infomaniak/core/myksuite/ui/network/ApiRoutes.kt

Depends on #412
Depends on #441

chore: Revert "Use preprod URLs"

---

FragmentNavigation/src/main/java/com/infomaniak/core/fragmentnavigation/FragmentNavigationExt.kt

feat: Add `safelyNavigate` for Activity

---

kSuite/kSuitePro/src/main/res/values-es/strings.xml
kSuite/src/main/java/com/infomaniak/core/ksuite/ui/utils/MatomoKSuite.kt

feat: Add kSuitePro Matomo
